### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by GildedHonour** [orionprotocol/orion-holochain#8]

**Comment by GildedHonour** [comment]
It compiles 

An error when running the tests

**Comment by GildedHonour** [comment]
```
hc package
hc test
```
===>


```
Error: artifact path /Users/alex/projects/rust/orion-holochain/zomes/orion_project1/code/target/wasm32-unknown-unknown/release/orion_project1.wasm either doesn't point to a file or doesn't exist

```

I asked about this in the chat

**Comment by GildedHonour** [comment]
fixed

Another one:

```
Exception occurred while calling zome function:  unable to call zome "broker" function "create_broker": InternalFailure(Dna(ZomeNotFound("Zome \'broker\' not found")))
Stopping instance "alice"...
not ok 1 unable to call zome "broker" function "create_broker": InternalFailure(Dna(ZomeNotFound("Zome \'broker\' not found")))

```

**Comment by GildedHonour** [comment]
Fixed

Another one:

```
Exception occurred while calling zome function:  unable to call zome "orion_project1" function "create_broker": InternalFailure(CapabilityCheckFailed)
Stopping instance "alice"...
not ok 1 unable to call zome "orion_project1" function "create_broker": InternalFailure(CapabilityCheckFailed)
  ---
```

**Comment by GildedHonour** [comment]
Fixed that, another one has appeared:



It should've worked, somebody has told me in the chat, however it doesn't . Probably due to the fact that the versions don't match up

**Comment by GildedHonour** [comment]
<img width="867" alt="Captura de pantalla 2019-05-05 a la(s) 15 29 06" src="https://user-images.githubusercontent.com/2032888/57199225-3520bd80-6f6c-11e9-84ec-1baec7ecdd47.png">

**Comment by GildedHonour** [comment]
I'll try different versions

**Comment by GildedHonour** [comment]
Now the first test will pass

<img width="857" alt="Captura de pantalla 2019-05-05 a la(s) 16 08 27" src="https://user-images.githubusercontent.com/2032888/57199716-a31bb380-6f71-11e9-9fcd-182d8796881b.png">

**Comment by GildedHonour** [comment]
Adding other stuff

**Comment by GildedHonour** [comment]
Current issue -- a test with errors in it test will pass successfully. 

Namely, `initialize_order` accepts multiple arguments.

Why will it pass - I don't know.

```
scenario.runTape("create broker", async (t, { alice }) => {
    // ok
    const res1 = alice.call("orion_project1", "create_broker", {"name": "broker1"});
    var {Ok: addr} = res1;
    t.deepEqual(res1.Ok, addr);

    //todo: why will it pass?
    const res2 = alice.call("orion_project1", "initialize_order", {"??name": "todo??"});
    var {Ok: addr2} = res2;
    t.deepEqual(res2.Ok, addr2); // Success
})
```

**Comment by GildedHonour** [comment]
I've created a branch "develop" locally.  

I have slow internet at the moment, I'll push it to this repo later.

**Comment by GildedHonour** [comment]
I'm looking into a way to update an entity. I haven't found one yet. In the examples it's done slightly differently. I've asked about that in the chat. 

It's needed to update the status of an Order: "new" -- /approve_order/ --> "approved" --> "open" --> "closed" --> "canceled"

**Comment by GildedHonour** [comment]
> I'm looking into a way to update an entity. 

Found it

**Comment by GildedHonour** [comment]
Regarding "to!" and "from!" with "agent_id%" --> I asked in the chat several days ago, there's been no reply yet.

**Comment by GildedHonour** [comment]
**1**

```holochain_core_types::entry::entry_type::EntryType.AgentID```

> That will get stringified into "%agent_id", as you say, but don't hard-code that, as it might change.


**2**

   **2.1** Alice wants to initiate a transaction with Bob, but notices he's offline. So instead of using node-to-node messaging, she publishes a "message" entry on the DHT, and creates a "message_notification" link from Bob's agent ID to her message. When Bob comes online, he checks for any "message_notification" links, follows them to the messages, then deletes the links once he's read the messages.

   **2.2** Charlie is a blogger who writes for a publication called "Apartment Gardening Weekly". He creates an "author_of_this_publication" link from the publication's entry on the DHT to his own agent ID, and he creates a "publications_i_write_for" link from his agent ID back to the publication. He might also want to create an "author_bio" link from his agent ID to his biography.

**Comment by GildedHonour** [comment]
Error when running a test:

```
Stopping instance "alice"...
not ok 3 unable to call zome "orion_project1" function "initialize_order": InternalFailure(RibosomeFailed("WASM invocation failed: Trap: Trap { kind: Unreachable }"))
  ---
    operator: fail
    at: Test.Scenario._tape (/Users/alex/projects/rust/orion-holochain/node_modules/@holochain/holochain-nodejs/index.js:191:23)
    stack: |-
      Error: unable to call zome "orion_project1" function "initialize_order": InternalFailure(RibosomeFailed("WASM invocation failed: Trap: Trap { kind: Unreachable }"))
          at Test.assert [as _assert] (/Users/alex/projects/rust/orion-holochain/node_modules/tape/lib/test.js:226:54)
          at Test.bound [as _assert] (/Users/alex/projects/rust/orion-holochain/node_modules/tape/lib/test.js:77:32)
          at Test.fail (/Users/alex/projects/rust/orion-holochain/node_modules/tape/lib/test.js:319:10)
          at Test.bound [as fail] (/Users/alex/projects/rust/orion-holochain/node_modules/tape/lib/test.js:77:32)
          at Test.Scenario._tape (/Users/alex/projects/rust/orion-holochain/node_modules/@holochain/holochain-nodejs/index.js:191:23)
          at <anonymous>
          at runMicrotasksCallback (internal/process/next_tick.js:122:5)
          at _combinedTickCallback (internal/process/next_tick.js:132:7)
          at process._tickCallback (internal/process/next_tick.js:181:9)
  ...
```

It's unclear what causes it

**Comment by GildedHonour** [comment]
Actually, the 1st test "create_broker" won't pass, the error isn't clear. It may be related to the way NodeJs de-/serializes data. That is, an entry will be created really, but the test won't pass.

**Comment by GildedHonour** [comment]
```
actual: |-
        { Internal: 'Argument deserialization failed' }
```

the struct 'Broker' has only 'name: String' in it. Strange

**Comment by GildedHonour** [comment]
Updated the version of Nodejs/holochain and the 1st test passes.

**Comment by GildedHonour** [comment]
Regarding the enum "Direction" in the tests --> the previous error is gone

```
InternalFailure(RibosomeFailed("WASM invocation failed: Trap: Trap { kind: Unreachable }"
```

A new one has appeared:

```
        { SerializationError: 'invalid type: map, expected unit at line 1 column 70' }
```

I've tried different types:

```
      //won't work
      "direction": {"Buy": {}},
      // "direction": {"Buy": 123},
      // "direction": {"Buy": undefined},
      // "direction": {"Buy": ""},
```

It expects `unit` or `void` for some reason

**Comment by GildedHonour** [comment]
**1)** 
```
let ts = SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_secs();
```


This isn't allowed due to its being random

**2)** the correct way to pass a enum as an argument is: `"direction": "Buy",`

**Comment by GildedHonour** [comment]
now the tests will pass

**Comment by GildedHonour** [comment]
When trying to approve an order, it won't get approved, its status will remain the same. This may be a bug in Holochain, as they told me in the chat.

**Comment by GildedHonour** [comment]
For signing data -- permitting to only those who know private key to call certain functions such as "create_order", we may or may not need:

https://developer.holochain.org/api/0.0.18-alpha1/hdk/api/fn.sign.html

https://developer.holochain.org/api/0.0.18-alpha1/hdk/api/fn.verify_signature.html

**Comment by GildedHonour** [comment]
It's unclear how it'd be implemented, I've not found any example.

**Comment by GildedHonour** [comment]
<img width="1192" alt="Captura de pantalla 2019-06-14 a la(s) 01 54 38" src="https://user-images.githubusercontent.com/2032888/59521889-e0525a00-8ebc-11e9-88f3-8d0cb59bf236.png">

**Comment by GildedHonour** [comment]
<img width="1208" alt="Captura de pantalla 2019-06-19 a la(s) 15 44 19" src="https://user-images.githubusercontent.com/2032888/59798772-7c6fcd00-92d2-11e9-836e-f91901ba9d8f.png">

**Comment by GildedHonour** [comment]
validation we need

https://gist.github.com/Connoropolous/c7bced4a5b1340b0136adbd793072189#file-lib-rs-L51

**Comment by GildedHonour** [comment]
I've added that.  Now I'm looking for a way of accessing an agent's address, in JS tests

**Comment by GildedHonour** [comment]
` hdk::AGENT_ADDRESS.to_string()` throws an exception when called from JS tests

**Comment by GildedHonour** [comment]
Regarding the task: How can we verify if a Trade is created by a certain Broker if there's no relationship between Trade and Broker?
